const PORT = process.env.PORT;
const EMAIL_VERIFICATION = process.env.EMAIL_VERIFICATION;
const EMAIL_HOST = process.env.EMAIL_HOST;
const EMAIL_USER = process.env.EMAIL_USER;
const EMAIL_PASSWORD = process.env.EMAIL_PASSWORD;
const JWT_SECRET_ACCESS_TOKEN = process.env.JWT_SECRET_ACCESS_TOKEN;
const JWT_SECRET_REFRESH_TOKEN = process.env.JWT_SECRET_REFRESH_TOKEN;

export {
  PORT,
  EMAIL_HOST,
  EMAIL_VERIFICATION,
  EMAIL_USER,
  EMAIL_PASSWORD,
  JWT_SECRET_ACCESS_TOKEN,
  JWT_SECRET_REFRESH_TOKEN,
};
