const PORT = process.env.PORT;
const EMAIL_VERIFICATION = process.env.EMAIL_VERIFICATION;
const EMAIL_HOST = process.env.EMAIL_HOST;
const EMAIL_USER = process.env.EMAIL_USER;
const EMAIL_PASSWORD = process.env.EMAIL_PASSWORD;

export { PORT, EMAIL_HOST, EMAIL_VERIFICATION, EMAIL_USER, EMAIL_PASSWORD };
